repository_type: pipeline
nf_core_version: 3.2.0
lint:
  files_unchanged:
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/branch.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows/branch.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .github/CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - assets/nf-core-radqc_logo_light.png
  - docs/images/nf-core-radqc_logo_light.png
  - docs/images/nf-core-radqc_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/CONTRIBUTING.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - assets/email_template.txt
  - docs/README.md
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
  multiqc_config:
  - report_comment
  files_exist:
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - .editorconfig
  - .prettierignore
  - .prettierrc.yml
  - .github/ISSUE_TEMPLATE/bug_report.yml
  - .github/ISSUE_TEMPLATE/feature_request.yml
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/CONTRIBUTING.md
  - .github/.dockstore.yml
  - .github/workflows/branch.yml
  - .github/workflows/ci.yml
  - .github/workflows/linting_comment.yml
  - .github/workflows/linting.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - .editorconfig
  - .prettierignore
  - .prettierrc.yml
  - CODE_OF_CONDUCT.md
  - assets/nf-core-radqc_logo_light.png
  - docs/images/nf-core-radqc_logo_light.png
  - docs/images/nf-core-radqc_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  readme:
  - nextflow_badge
  - nextflow_badge
  - nextflow_badge

template:
  org: NationalGenomicsInfrastructure
  name: radQC
  description: Pipeline for QC of RAD-seq data
  author: "Remi-André Olsen"
  version: 0.3.2
  force: true
  outdir: .
  skip_features:
  - github
  - ci
  - igenomes
  - github_badges
  - code_linters
  - gitpod
  - codespaces
  - vscode
  is_nfcore: false
