name: nfcore-radseq-0.1.2dev
dependencies:
  - conda-forge::r-base=3.4.1
  - conda-forge::r-markdown=0.8
  - bioconda::fastqc=0.11.7
  - bioconda::multiqc=1.11
  - bioconda::stacks=2.4
  - bioconda::trimmomatic=0.38
