name: nf-core-radseq-0.1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::r-base
  - conda-forge::r-markdown
  - bioconda::fastqc=0.11.7
  - bioconda::multiqc=1.5
  - bioconda::stacks=2.1
  - bioconda::trimmomatic=0.38
