name: radseqqc-0.1.3dev
dependencies:
  - conda-forge::r-base=3.4.1
  - conda-forge::r-markdown=1.1
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.11
  - bioconda::stacks=2.61
  - bioconda::trimmomatic=0.39
